version: "3"
services:
    flaskapp:
        build: .
        depends_on:
            - database
        ports:
            - "5000:5000"

    database:
        image: postgres:latest
        environment:
            - POSTGRES_PASSWORD=toto_pwd
            - POSTGRES_USER=toto_user
            - POSTGRES_DB=toto_db
        restart: always